name: Test

on:
  push:
    branches-ignore:
      - main
      - staging*
      - production*

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: sample_mysql_test

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: apt-get update
        run: sudo apt-get update -y

      - name: Verify MySQL connection from host
        run: |
          sudo service mysql restart
          sudo apt-get install -y libmysqlclient-dev
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }}  -uroot -proot mysql
      - uses: actions/checkout@v2
      - name: Read Gemfile
        run: echo ::set-output name=RUBY_VERSION::$(cat Gemfile|grep "ruby '"|awk -F"'" '{print $2}')
        id: gemfile

      - name: Set up Ruby ${{ steps.gemfile.outputs.RUBY_VERSION }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.gemfile.outputs.RUBY_VERSION }}

      - name: Install Bundler
        run: gem install bundler

      - name: Bundle Install
        run: bundle install --jobs 4 --retry 3

      - name: Migrate
        run: bundle exec rails db:migrate:reset

      - name: Test
        run: bundle exec rspec
